server:
  port: 8100

spring:
  profiles:
    active: dev # 环境 dev|test|prod
  application:
    name: harbor-platform
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    hikari:
      maximum-pool-size: 20          # 默认10，根据并发量调整
      minimum-idle: 10
      connection-timeout: 5000       # 5秒获取不到连接就失败
      idle-timeout: 300000           # 空闲连接5分钟回收
      max-lifetime: 1800000          # 连接最大存活30分钟
      leak-detection-threshold: 30000 # 连接泄漏检测
  threads:
    virtual:
      enabled: true
  main:
    keep-alive: true  #保活，避免应用只剩虚拟线程时 JVM 提前退出

mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID # 雪花算法
  configuration:
    map-underscore-to-camel-case: true #开启自动驼峰命名规则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  accessToken:
    expireIn: 1800 #半个小时
    secret: MIIBIjANBgkq
  refreshToken:
    expireIn: 604800 #7天
    secret: IKDiqVmn0VFU

harbor:
  perf:
    auth:
      skip-captcha: false
