spring:
  profiles:
    active: dev
  application:
    name: harbor-server

websocket:
  enable: true
  port: 8101

tcpsocket:
  enable: false # 暂时不开启
  port: 8102

jwt:
  accessToken:
    secret: MIIBIjANBgkq # 跟im-platfrom的secret必须一致

harbor:
  mq:
    private-message:
      consumer:
        consume-thread-min: 64
        consume-thread-max: 128
        consume-message-batch-max-size: 32
        pull-batch-size: 64
    group-message:
      consumer:
        consume-thread-min: 64
        consume-thread-max: 128
        consume-message-batch-max-size: 32
        pull-batch-size: 64
